version: "3"

services:
  web:
    build: .
    image: ghcr.io/sakura-tel/misskey-v11:latest
    restart: always
    links:
      - db
      - redis
#      - es
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - internal_network
      - external_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:3000/health || exit 1"]
    volumes:
      - ./files:/misskey/files
      - ./.config:/misskey/.config

  redis:
    restart: always
    image: redis:4.0-alpine
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - ./redis:/data

  db:
    restart: always
    image: postgres:12.2-alpine
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "example-misskey-user"]
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data

#  es:
#    restart: always
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    networks:
#      - internal_network
#    volumes:
#      - ./elasticsearch:/usr/share/elasticsearch/data

networks:
  internal_network:
    internal: true
  external_network:
